output_dir: ~/scratch/experiments/

dataset:
  class: biomedical
  path: ~/nbfnet_hy/data/PC_KEGG_0928
  include_factgraph: yes
  fact_as_train: yes
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: TransE
    embedding_dim: 128
    max_score: 6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 1
  sample_weight: yes

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4096

train:
  num_epoch: 100

metric: mrr