output_dir: ~/experiments/

dataset:
  class: biomedical
  path: /home/mila/y/yue.hu/github/NBFNet/data/PC_KEGG
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no



optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 64
  

train:
  num_epoch: 2
  batch_per_epoch: 1000

metric: mrr