output_dir: ~/experiments/

dataset:
  class: biomedical
  path: ./data/PC_KEGG
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  gene_annotation_predict: False
  conditional_probability: False



optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  

train:
  num_epoch: 8
  batch_per_epoch: 100
  
metric: mrr